# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_ols_normal_eq <- function(X, y) {
    .Call(`_mylm_cpp_ols_normal_eq`, X, y)
}

